apiVersion: k8s.mariadb.com/v1alpha1
kind: ExternalMariaDB
metadata:
  name: legacy-mariadb
  namespace: databases
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: legacy
    app.kubernetes.io/part-of: blogs-infrastructure
spec:
  host: mariadb.mariadb.svc.cluster.local
  port: 3306
  username: root
  passwordSecretKeyRef:
    name: mariadb-credentials
    key: mariadb-root-password
  tls:
    enabled: false
    required: false
