apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - argocd-application.yaml
  - certificate-config-application.yaml
  - external-dns-config-application.yaml
  - platform-applicationset.yaml
