# NEVER COMMIT UNENCRYPTED SECRETS TO GIT!
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-dns01
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2Hiky3FJkluref1/ZGCvLs9TZ9Nq/O/iQH10MVEoINmIvq9866zxZw==,iv:vrijxKB5W3FBhHQtg27SCCfobXd0eCaXxbCwVkoOBBQ=,tag:N1+uim/L4zSsfqkPpgZ+oA==,type:str]
sops:
    age:
        - recipient: age14ajguq07xzyd8pfyr79x4gwhd7jx7adnmfgd3d8sljxpumnxrycs7mc267
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV3VXNHJVYm05N09UQ01o
            ekJISVoxdFVPNW55bDlRcmI4a3R3N0JNblVNCjBqdnRLUUQza2lKUThSZjYvZmFL
            R05OZmdSSlM5QWxnRElYYTZ0UUFVQXcKLS0tIEZYa3d1WUgvYjRRbk5CcWlJYlF0
            QnNDZC9pMmgxUDk1dG1FNWh3Zy9yeHMKkBwdj4h/h4+/rvygSKnN1ne6m2/LClc9
            Ik/vdeM69rw3y/Rjr9yQRMFjM0/m83qDBwaMV+K5TA70CaJV3tID8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T05:42:52Z"
    mac: ENC[AES256_GCM,data:z1NZ9VC/1W+eLFa2cUND10unl5oAgs5QfIk2X7uGuT589RSDC3a343m6XoV7vWicd019T+mzKPenS0bIR2Ls5jWjn+0esSWz+n8TlhKBf3BJI8FEEgfCDnjAStKB97pX9o3YUqWlEVozplhnLLTB1z4hRdry/Zv9ebMJaII2+lk=,iv:yi4nZ98g6lVvONHrCLwg2wpe5E5AmOkjMprEo23FEAE=,tag:YEAUgJ0yZRckfhXCH5SW9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
