---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-credentials
  namespace: databases
spec:
  encryptedData:
    mariadb-password: AgCTVRDbEQh2q67HZM3ucq1f9sHftqDw6wC+MlXlf2N7jPq48lrpYDJYiktxXvV0OM3tIsvMfXVmdfqRT6cEMv946Ep4kuqot/rFQJPsedFMvnDPReNyyQi56NKyBVFWWy0VIamOnlGOvycaibFlCjZFwH/Vq8TQdFMWHtlUFioBeGEtKWT4hj/SzSRlEy2fYCA7ct+a7JNJLvHUe4+egJVWDnDo0NJWhiEj+O50PRleH6xPm97fnfNKwPqmspjn6KjORJl5YxmPola1XfPun/KU/8DYwPki85mT7SoE1PaJ/C+ARslPgRQ/fiycFv9a9GghE0KVMo3J4ag8hAbAAK2PzFbCmSgHCxlwfiwWnb6yQTvgLgVej0MAVkQ8yuWVxMUUNBjgzlNXPo7B/89BPe0Rk6tWyCLQIWbwuJ8TBy8anvb2QQYZqpHPHBzLqg3j5DQ3TnFzb2gSt8TkEBqDgIUa4dNiVDyuhN00JsllCrdl/nTU/IPi2jNso1v0LUu+47WNzqZBl95Z804W/Pq7tQp44mRbK2pFGocYlc0EvVmwOGDjyV8RX6qjLlHjvIVVHG/FDaAOU0SctWSvyJZ24uCNhTXVA7vAVl80cROslmjGTMa516Tk9CtocPPptig3rBF6yxeUAz296X9ZlhIUADj2XLPwNesBbsGfUswZiwRQlNwfvOpbTwHYyfNWPhlChQ5ZI0piBLIG65Qe9C0= # gitleaks:allow
    mariadb-root-password: AgCTCRlTDAtJtTfSrL016iN7LRXd41T1DdX5UVewwHwQFkmZES3gYLn0ANHDoGoEeMYnaY4XmCxKm/L2UU2K69ZYY9Cm0R/vALFIsrhkTOnjk9OJYOH/CdQbTBH5jpyJN4/z8629YOWVciT2vQs08B+MzWNj3btItXyGcD2oHv4AChpJ0PTO3HmN8xVwt18axRGri0ThnyH7IvDGlFMq9R+1RWtSD8XQyHa/U5uR7D5cpxBzW8Hnb3I3fJp6iRPVyqRgOJILQTgqoeDzlQgPoDvc3uooZYbzgJUrmvwS8UIt1/VM075Ak/vSIGa2n1HK7sX7NMpHpSHGKMfK3nMLkWP8w9iaUlkNYpohSVsEN7AFwlKrq4rhtmxNGMJn9Kl2+rtn1pe/nQaU0noh6MmXB1D5rpRAa1S2JLKUEG+oAyKw1oJSVGxQRUo2iVcY5y/Ci1DSBqB3GCfyx3Q5oCF1DVnrCPO3qN2RuxaURvonZ5Ax607AvO8OKu/nvnV8M3dBQ5zL9mS4d6U35U/8x+DCUH/uV8Ot2EzJRj/uoUQxoLXqHyc2fVw4yJPgP1AOsiykRaH6muzndk8dI9bT/PTAGYG9BiGVmboY5zXvwnwpWhzjvjPMF+3J1o2YIiOMCzk5oQQo+Pu1GmHq+KPgvLUhMtcRRSgXjejYB68qZ8b1nvBRtAGytg2JA7Kvt4Lgp5uqHEjuITXELUsuaRiJ8ug= # gitleaks:allow
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-credentials
      namespace: databases
    type: Opaque
