---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-r2-credentials
  namespace: databases
spec:
  encryptedData:
    access-key-id: AgCBGq4KTXOi1qMuVkWpbey9wZg1q0TA4Lfgj/HAu3bMa6m6HC9nzkblk76amIHRAt34gJq1UoO/zzKbI5iOn81Xn/3RyF5NNBkPLPp65m2obdV0Wmn6kSF+iMFMB3UzMZBF6B+97fzlgGMu4kSqINbfjPAcGn6pnj7xTX0VK/SK5RYOZRKLrGLDLaRCH4BvwUBkia3AH58pcSLupdAd9QKKHyekop/PFSsayNg0Ev11N5rP68BIRW6dVDZ3qQ9hUJOvKkNY0eWdLMqs4SSHIXIXtzKAFUAIUhI4VIfmlgadpnwSBdo8qzs/sGhwO6K9jdJCpFSuqCFvcOTY9lYqebR5OEy1AxrqGgHUyPVyAVAHHREevE2M/slFgIvReC1WnCrHFLRPeyHCflD7bah7D2RSuB6EzaQRYf5L3rAV+WoAMQmxiDZN/2i9MpSW/LdfqYEm4dhXCDn2MNAHqHJlB4SzXSxhexxB45WqT4WYGsVzgR9ddfw9A9w3n2nCdpeS1Z+uviVwlYnY/24pSDL8lpgVed4whgsPClE65Owxfika26eTniYr6tUfRgdxooPOudf0d/NJU2dx9NCQq1eKtE9gRgMtYGfw4tVy/peS8BCrn8Yfract3p027nGiHL410eFz7G89FkzIrMBzaQcSkihGnZcHB7aeaAmYhRLgyQ5QCkzc4YkoKyH8TaxeEHJvvXs+jo/sKDlyI8eha8uF2eRH/NA+xZRRY3z849gPrbtyTA== # gitleaks:allow
    secret-access-key: AgBwuQMfAoKSdZrfe6gFMyQ0z+1b9wV4XKwXVZXY8g47aFpTZMIo1aEW0hjIrOmggQ50rCm2uoaMvvoLZh+UXshVZOMJFKsAu4CLgebNTwFBJ3mppWEAJd6uNao2oo3MlG7T+e5spfgKtOZfSuCMKi/uixI96DDjfaH6aVAMnT0WKPUsVm2ZFxIlszeNNXq1C8R8MfZYfZUftRdCzTQmsujvIP+2+PTVgOEkHoLCj+raAmGSF96dno5CoAJ6pJ6J5xNZwtSjWmgfpF9m7oahgBajPH/1XlmankPDQbrtd8z7To/Q60mHAqthCtdsNeBuKZQuPvPakNjPhhAh950pXwZfIpQLDVNcbrIVOjIPwpEcnVMBmUp2hgi82eUCGIeNHoyZL6U8n29C/pvOIJU7bf54oM4CUzzHKxMAfw/JX2CUJdoHj59Fkw5jshSkP79HH/M/rT2OqTgz7dO6VAlqqyEUwblqPMlUzQrfMSKHbE7GysC8kH0hUKxP+FbcWeerqZWd76xH1Iy7Q5laCAOnDH1zrSHBhZ/s3Gu2UAqFVfkDPMuLY+xWZV+/+6qRplRlLACJ5QTK+kTi0gFIVCxX2MVN5AHIoEW+9tNxfMn6ZdXg0U9uMzpiiX41Df184WI+l1OGqd40DEfzmIw9v702Otgu7liKyWKrdFcvUwuRy4KhQS6l58JmzrQIdyZcMlYBof+gHoS7WgENK25lzIbyYXFO0fd+E9gwPUI8afU1r+JwUjJl/wewsaQZt+p22A2B5Nb4FODiXW12c+Ln8QLdqmhO # gitleaks:allow
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-r2-credentials
      namespace: databases
