---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBYq1qFICw7Opdd0VmkcIfP7wB7gyknWnBzxYN9pdRGchycsC+cqSlI0aHMhWf8qXn522a//TSv31BuSi6E5n4WPTxGLbCICkTH5NDvxTHA23ZbYAKIoEofy051hEf6fBq+R++cUSFF75e0pY0TaGIB+fSNuWaZpvL85+WOYsiOaLBl7fugYHMIvfb8F6XokV6ly/+3l9w+54/DIN3+IothXYYmXCJOCpHv/nJwd8fPkmU/Es61D3qk5UthNg8rx4OKTRQGlnZIdRcxRDk68NqHyIOxYbybllxvzFZAbjbrERGqns59yEFN915PkeGrKVlfio5r6V5q+YjAp8QYRi5xAiZxRhJzJB+emXi4XoV1o3NIcQODRVhtmz0MBD5tC/zCiN0QCgAhj+J+qh/uODXp3BQWzhs45zDd687TTNF6+is7XtfqF0IMfIrxuG9wRzYMY9cSXKKW+jPQfafsYmdfxQClVjyfcJG6eiUkIlP0OmxeQlwS+C+E6qIz3TgA2qNFHQXBgl2lQSwz+tCmzeE8/UX+mjcXDbuSxHlyK+Yn7uRGpsbZhK+pUCmaydEesqI9awIOVcSHft4PKfyepHooo74sucywPcjfOVfeafARGPXLnB5NmA3tEUuxBTkhjRtcamxsKxJH6NEJnsz3hlynuqKKgM9hKzXH/yWiYt9MOjObdqnZoDj1H2zc2JgXRallhhJMaVuX2R7RRRI98qFWuTdbUVyHsu3APsM2S+YOyqB0mp9eTT/K