---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis-ns
spec:
  encryptedData:
    redis-password: AgCW4xT9Tsn1zPGuzm97xFTqPmrSjnKVZGj+orYv7LtrcWjpHTrLZggi0Gq0691rD/LyZpnqaUWPFaS7j6Pm0QaYWYoi38+I0qDn6UeuutcSYhaWKaWAj7TgmdCyU0htIBBaNuVZtYxdL0gKimd6wuDPaudv/zRjsQaMQHOJcAZLcG1OaxnPew57MfrY4X9O/mzuZPQQ8m0Ex0EznxU2Swvrjqh1ayvh/1Vkg5eTWj+6V1Q37aWEwg/FTi8glu5GgsmZDzOl7dKoRR4fRGot9erDACUk1ZwMSUCeoejpoYpqPpjYj3GE2oRVEHXUY9I5HXoXEGbCmoVvmIUensqgZ0mXXFElzdwJ6z+epPiWQ+F/tkJxPNWF7Qv2zI5oodICrRNlCva+AXo1OXO5a9fxvLCaRCtnDxxYdIUQLyNXKU1Q/f69YlYCUxG0qU+7XgmdJ4mTWbppc6m+sr5KpR/dBT5K1HKDbLoUttArJWJh4TKGhYVgWiOHScn3M+2fNQmINEsl21D68UnH/FJS1iswpwQ9xAWcEWsW+PLRU/9eBOIdsqtN0CCRRa4AhV+ACqbTzMMWpGWrTNShNZXV8gZJqAeEMDCawsYbb5YMwahYH0qQwOaDuIhJciSLpebarEi6kjH/RKF1liddDCljRnj/RgK3ykqXiuz3qNc3CapFuzcw76056EkF5ZdLVviX5PDp98tQgvjcIiCqMNI=