---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wpsites-tls
  namespace: ingress
spec:
  secretName: wpsites-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  commonName: wpsites.douglasbarahona.me
  dnsNames:
    - wpsites.douglasbarahona.me
