---
# Flux Kustomization for gateway
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/prod/infra/gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
    - name: issuers
---
# Namespace for gateway resources
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    name: ingress
    pod-security.kubernetes.io/enforce: baseline
---
# Gateway resource using Cilium GatewayClass
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: ingress
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-firewall: "true"
    service.beta.kubernetes.io/do-loadbalancer-firewall-allow-from: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
# HTTPRoute for HTTP -> HTTPS redirect
# This catches all HTTP traffic and redirects to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: ingress
spec:
  parentRefs:
    - name: public-gateway
      namespace: ingress
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
# (Certificates intentionally removed; apps will create via Ingress annotations.)
