# TODO: Replace this with SOPS-encrypted secret
#
# Generate the token:
#   openssl rand -hex 32
#
# Update the secret below, then encrypt with SOPS:
#   sops --encrypt --in-place secret-origin-verify-token.yaml
#
# IMPORTANT: Use the SAME token value in your Cloudflare Transform Rules!
#
# NEVER COMMIT UNENCRYPTED SECRETS TO GIT!
apiVersion: v1
kind: Secret
metadata:
    name: origin-verify-token
    namespace: ingress
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:83wu4aIyD0Z52TUOZbFdpz4U+lU+4HRzrvlyRtZyEAXCWCONwAdWvKnnYwWjvv96ZZ5xYf9tX2xfsIhrn8lvsg==,iv:ZNkOC+Syi+I4Hzb2Zu7n7bGgQDBAesVlVH7W8WGY+Bw=,tag:UyN6BQVD8vGRhMlMfuaK/A==,type:str]
sops:
    age:
        - recipient: age14ajguq07xzyd8pfyr79x4gwhd7jx7adnmfgd3d8sljxpumnxrycs7mc267
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N0N5RzRVQVAwUXIzTkJh
            RnMxalJUT2hXYTR3ditBd3BYZDYxanFmRVRrCjluUFE1WCt6dXFUZC8rbnVTYkhY
            TVNvMElsNVBJb1czRTJRR1QzQmwvSm8KLS0tIGhSUnIyblJuR0MvVE91VmFrWTRi
            eWJPRGZmL3JCdkw2MjhOdExXcWhXOEEKMFdoE1/wwJTwPqKfqAz0qoT4TDb9MDK8
            2r50kUaHVlu6phzoMlfjHsY+1LFW2WiStOYwSCpqhww6anDzt3ahAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T05:52:05Z"
    mac: ENC[AES256_GCM,data:3XDCWDLfSLy9tb+gAolRope00vN9S5uzEOlih/irO3mknxIfzskQXnBW+NZCp/aNvk5nCm4Yj85dhafwEFJkWOZ89RLsp+iD/RnWiWXznhzEMhWU27O0cAYYhaKwKD0w9bto7vQXRYBOnSDxf36MBD65czpdsJyREx+tItjESo0=,iv:rLQlVxsDp8AlT5dFDrHHG21Osr1IOXvGXRw06qmrtR4=,tag:GbCJSCzH53s8ga8ampyeEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
