---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kustomize-prod-alerts
  namespace: flux-system
spec:
  providerRef:
    name: slack-prod
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: flux-system
  inclusionList:
    - ".*ReconciliationFailed.*"
